# Generated by Django 3.0.8 on 2020-07-27 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='creator',
        ),
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
