# Generated by Django 3.0.8 on 2020-07-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200728_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityentry',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectcontributor',
            name='activity_viewer',
            field=models.BooleanField(default=False),
        ),
    ]
