# Generated by Django 3.0.8 on 2020-07-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200728_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontributor',
            name='project_admin',
            field=models.BooleanField(default=False),
        ),
    ]
