# Generated by Django 3.0.8 on 2020-08-01 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200729_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityentry',
            name='creator',
        ),
        migrations.AddField(
            model_name='activityentry',
            name='contributor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ProjectContributor'),
            preserve_default=False,
        ),
    ]
